version: 2

sources:
  - name: raw # This is the logical name for the dataset
    schema: gz_raw_data
    tables:
      - name: sales
        description: "Contains historical sales data up to 2021."
        identifier: raw_gz_sales # The actual table name in the database
        loaded_at_field: "CAST( date_date AS TIMESTAMP)"
        freshness:
          warn_after: { count: 90, period: day } # Warn if the latest data is older than 90 days

        columns:
          - name: date_date
            description: date of purchase
          - name: orders_id
            description: primary key
          - name: product_id
            description: number of indentification of these products
          - name: revenue
            description: income of theses sales
          - name: quantity
            description: quantity of these sales
        tests:
          - unique:
              column_name: "(orders_id || '-' || pdt_id)"

      - name: product
        identifier: raw_gz_product
        columns:
          - name: products_id
            description: primary key
            tests:
              - unique
              - not_null

          - name: purchase_price
            description: price of these purchase by product id
      - name: ship
        identifier: raw_gz_ship
        columns:
          - name: orders_id
            description: primary key
            tests:
              - unique
              - not_null

          - name: shipping_fee
            description: fee of these shipping
          - name: logcost
            description: logistic cost
          - name: ship_cost
            description: cost of these shipping
      - name: adwords
        identifier: raw_gz_adwords
        columns:
          - name: date_date
            description: date of ads
          - name: paid_source
            description: paid
          - name: campaign_key
            description: campaing
          - name: camPGN_name
            description: name of campaing
          - name: ads_cost
            description: cost ads
          - name: impression
            description: impressions
          - name: click
            description: clicks
      - name: bing
        identifier: raw_gz_bing
        columns:
          - name: date_date
            description: date
          - name: paid_source
            description: paid
          - name: campaign_key
            description: campaign
          - name: camPGN_name
            description: name campaign
          - name: ads_cost
            description: ads cost
          - name: impression
            description: impressions
          - name: clicks
            description: click
      - name: criteo
        identifier: raw_gz_criteo
        columns:
          - name: date_date
            description: date
          - name: paid_source
            description: paid
          - name: campaign_key
            description: campaign
          - name: camPGN_name
            description: campaign name
          - name: ads_cost
            description: ads cost
          - name: impression
            description: impressions
          - name: click
            description: clicks
      - name: facebook
        identifier: raw_gz_facebook
        columns:
          - name: date_date
            description: date
          - name: paid_source
            description: paid
          - name: campaign_key
            description: campaign key
          - name: camPGN_name
            description: campaign name
          - name: ads_cost
            description: ads cost
          - name: impression
            description: impressions
          - name: click
            description: clicks
